# Site settings
title: "Jack.Z"
description: "Not just a coder."
baseurl: ""
url: "http://i.easyapple.net"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "abt"
    url: /about
  - title: "git"
    url: https://github.com/undersail
  - title: "rss"
    url: /feed.xml
