# Site settings
title: "Jack.Zheng"
description: "Not just a coder."
baseurl: ""
url: "http://i.easyapple.net"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "about"
    url: /about
  - title: "github"
    url: https://github.com/undersail
  - title: "rss"
    url: /feed.xml
